function [f]=NLequations(theta)
f(1)=150*cos(theta(1))*sin(theta(2)) - (27*sin(theta(1)))/2 + (38*cos(theta(4))*sin(theta(1)))/5 + 5*sin(theta(1))*sin(theta(4)) - (394*cos(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))))/5 + 5*cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))) - (38*sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))/5 + (394*sin(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))))/5 - (3147*cos(theta(1))*sin(theta(2))*sin(theta(3)))/20 + (3147*cos(theta(1))*cos(theta(2))*cos(theta(3)))/20 - 5*cos(theta(1))*cos(theta(2))*sin(theta(3)) - 5*cos(theta(1))*cos(theta(3))*sin(theta(2))+11.5;
f(2)=(27*cos(theta(1)))/2 - (38*cos(theta(1))*cos(theta(4)))/5 - 5*cos(theta(1))*sin(theta(4)) + 150*sin(theta(1))*sin(theta(2)) + (394*cos(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))))/5 + 5*cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))) - (38*sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))/5 + (394*sin(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1))))/5 - 5*cos(theta(2))*sin(theta(1))*sin(theta(3)) - 5*cos(theta(3))*sin(theta(1))*sin(theta(2)) - (3147*sin(theta(1))*sin(theta(2))*sin(theta(3)))/20 + (3147*cos(theta(2))*cos(theta(3))*sin(theta(1)))/20-320.9;
f(3)=150*cos(theta(2)) - 5*cos(theta(2))*cos(theta(3)) - (3147*cos(theta(2))*sin(theta(3)))/20 - (3147*cos(theta(3))*sin(theta(2)))/20 + 5*sin(theta(2))*sin(theta(3)) + 5*cos(theta(4))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3))) - (38*sin(theta(4))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3))))/5 + (394*sin(theta(5))*(cos(theta(2))*sin(theta(3)) + cos(theta(3))*sin(theta(2))))/5 - (394*cos(theta(4))*cos(theta(5))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3))))/5 + 656/5-95;
f(4)=cos(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) - sin(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3)))+0 ;
f(5)=- sin(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) - cos(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3)))-0 ;
f(6)=sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))) - cos(theta(4))*sin(theta(1))+1;
f(7)=- cos(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))) - sin(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1)))+0.5;
f(8)=sin(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))) - cos(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1)))-0.8660;
f(9)=cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))-0;
f(10)=cos(theta(4))*cos(theta(5))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3))) - sin(theta(5))*(cos(theta(2))*sin(theta(3)) + cos(theta(3))*sin(theta(2)))- 0.8660;
f(11)=- cos(theta(5))*(cos(theta(2))*sin(theta(3)) + cos(theta(3))*sin(theta(2))) - cos(theta(4))*sin(theta(5))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))-0.5;
f(12)=sin(theta(4))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))-0;
















%f(4)=-asin(cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))- 0.2522;
%f(5)=atan2(sin(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) + cos(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))), cos(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) - sin(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))))-1.4437;
%f(6)=atan2(- cos(theta(1))*cos(theta(4)) - sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))), sin(theta(4))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3))))+1.4149;
% f(4)=-atan((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))/(cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))))-4.5207;
% f(5)=-atan(((cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))/((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))^2/(cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))^2 + 1)^(1/2) + (cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))^2/((cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))*((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))^2/(cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))^2 + 1)^(1/2)))/(sin(theta(4))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))))+1.3560;
% f(6)=-atan(((cos(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))) + sin(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1))))/((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))^2/(cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))^2 + 1)^(1/2) - ((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))*(cos(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) - sin(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3)))))/((cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))*((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))^2/(cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))^2 + 1)^(1/2)))/((sin(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))) - cos(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1))))/((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))^2/(cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))^2 + 1)^(1/2) - ((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))*(sin(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) + cos(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3)))))/((cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))*((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))^2/(cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))^2 + 1)^(1/2))))+0.0908;
% 

%f(4)=-atan(((sin(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) + cos(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))))*(sin(theta(5))*(cos(theta(2))*sin(theta(3)) + cos(theta(3))*sin(theta(2))) - cos(theta(4))*cos(theta(5))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))) + (cos(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) - sin(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))))*(cos(theta(5))*(cos(theta(2))*sin(theta(3)) + cos(theta(3))*sin(theta(2))) + cos(theta(4))*sin(theta(5))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))))/((sin(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) + cos(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))))*(cos(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))) + sin(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1)))) - (cos(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) - sin(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))))*(sin(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))) - cos(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1))))))+1.4326;
%f(5)=-atan((cos(theta(4))*sin(theta(1)) - sin(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2))))/((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))^2 + (sin(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) + cos(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))))^2 + (cos(theta(5))*(sin(theta(1))*sin(theta(4)) + cos(theta(4))*(cos(theta(1))*cos(theta(2))*sin(theta(3)) + cos(theta(1))*cos(theta(3))*sin(theta(2)))) - sin(theta(5))*(cos(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(1))*cos(theta(2))*cos(theta(3))))^2 + sin(theta(4))^2*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))^2)^(1/2))-0.0805;
%f(6)=atan(((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))*(sin(theta(5))*(cos(theta(2))*sin(theta(3)) + cos(theta(3))*sin(theta(2))) - cos(theta(4))*cos(theta(5))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))) - sin(theta(4))*(cos(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))) + sin(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1))))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3))))/((cos(theta(1))*cos(theta(4)) + sin(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2))))*(cos(theta(5))*(cos(theta(2))*sin(theta(3)) + cos(theta(3))*sin(theta(2))) + cos(theta(4))*sin(theta(5))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))) + sin(theta(4))*(sin(theta(5))*(cos(theta(1))*sin(theta(4)) - cos(theta(4))*(cos(theta(2))*sin(theta(1))*sin(theta(3)) + cos(theta(3))*sin(theta(1))*sin(theta(2)))) - cos(theta(5))*(sin(theta(1))*sin(theta(2))*sin(theta(3)) - cos(theta(2))*cos(theta(3))*sin(theta(1))))*(cos(theta(2))*cos(theta(3)) - sin(theta(2))*sin(theta(3)))))+1.4469;
